/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  romolaSidebar: [
      {type: 'autogenerated', dirName: '.'}
  ],
  middleMarchSidebar: [
    {
      type: 'html',
      value: "<div id='book-title'>📖 Middlemarch <div> ",
      className: 'sidebar-title book-header'
    },
    {
      type: 'doc',
      id: 'middlemarch/index'
    },
    {
      type: 'doc',
      id: 'middlemarch/PRELUDE'
    },
    {
      type: 'html',
      value: "<div style='padding-top:10px'>BOOK I. MISS BROOKE.<div>",
      className: 'sidebar-title book-title',
      defaultStyle: true,
    },
    {type: 'autogenerated', dirName: 'middlemarch/BOOK I'},
    {
      type: 'html',
      value: "<div style='padding-top:10px'>BOOK II. OLD AND YOUNG.<div>",
      className: 'sidebar-title book-title',
      defaultStyle: true,
    },
    {type: 'autogenerated', dirName: 'middlemarch/BOOK II'},
    {
      type: 'html',
      value: "<div style='padding-top:10px'>BOOK III. WAITING FOR DEATH.<div>",
      className: 'sidebar-title book-title',
      defaultStyle: true,
    },
    {type: 'autogenerated', dirName: 'middlemarch/BOOK III'},    {
      type: 'html',
      value: "<div style='padding-top:10px'>BOOK IV. THREE LOVE PROBLEMS.<div>",
      className: 'sidebar-title book-title',
      defaultStyle: true,
    },
    {type: 'autogenerated', dirName: 'middlemarch/BOOK IV'},    {
      type: 'html',
      value: "<div style='padding-top:10px'>BOOK V. THE DEAD HAND.<div>",
      className: 'sidebar-title book-title',
      defaultStyle: true,
    },
    {type: 'autogenerated', dirName: 'middlemarch/BOOK V'},    {
      type: 'html',
      value: "<div style='padding-top:10px'>BOOK VI. THE WIDOW AND THE WIFE.<div>",
      className: 'sidebar-title book-title',
      defaultStyle: true,
    },
    {type: 'autogenerated', dirName: 'middlemarch/BOOK VI'}, 
    {
      type: 'html',
      value: "<div style='padding-top:10px'> BOOK VII. TWO TEMPTATIONS.<div>",
      className: 'sidebar-title book-title',
      defaultStyle: true,
    },
    {type: 'autogenerated', dirName: 'middlemarch/BOOK VII'}, 
    {
      type: 'html',
      value: "<div style='padding-top:10px'> BOOK VIII. SUNSET AND SUNRISE.<div>",
      className: 'sidebar-title book-title',
      defaultStyle: true,
    },
    {type: 'autogenerated', dirName: 'middlemarch/BOOK VIII'}, 
    {
      type: 'html',
      value: "<div style='padding-top:10px'> FINALE.<div>",
      className: 'sidebar-title book-title',
      defaultStyle: true,
    },
    {type: 'doc', id: 'middlemarch/FINALE'},
  ]
};

module.exports = sidebars;
